-- Création de la table "RoleUser"
CREATE TABLE RoleUser (
    NOM_ROLE_USER VARCHAR(30) PRIMARY KEY
);

-- Insertion des rôles possibles
INSERT INTO RoleUser (NOM_ROLE_USER) VALUES
    ('utilisateur'),
    ('admin_web'),
    ('admin_sys'),
    ('technicien'),
    ('missingno');

-- Création de la table "Utilisateur"
CREATE TABLE Utilisateur (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_USER VARCHAR(20) UNIQUE CHECK (LENGTH(LOGIN_USER) >= 5),
    PRENOM_USER VARCHAR(30),
    NOM_USER VARCHAR(30),
    ROLE_USER VARCHAR(30),
    EMAIL_USER VARCHAR(100) CHECK (EMAIL_USER REGEXP '^[A-Za-z0-9._%-]+@[A-Za-z.-]+\\.[A-Za-z]{2,4}$'),
    HORODATAGE_OUVERTURE_USER DATETIME CURRENT_DATE(),
    HORODATAGE_DERNIERE_CONNECTION_USER DATETIME,
    IP_DERNIERE_CONNECTION_USER VARCHAR(15),
    FOREIGN KEY (ROLE_USER) REFERENCES RoleUser (NOM_ROLE_USER)
);

-- Création de la table "EtatTicket"
CREATE TABLE EtatTicket (
    VALEUR_ETAT_TICKET VARCHAR(30) PRIMARY KEY
);

-- Insertion des états possibles
INSERT INTO EtatTicket (VALEUR_ETAT_TICKET) VALUES
    ('en_attente'),
    ('ouvert'),
    ('en_cours_de_traitement'),
    ('ferme');

-- Création de la table "Ticket"
CREATE TABLE Ticket (
    ID_TICKET INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT,
    OBJET_TICKET VARCHAR(100),
    DESCRIPTION_TICKET VARCHAR(250),
    ID_TECHNICIEN INT DEFAULT NULL,
    NIV_URGENCE_ESTIMER_TICKET VARCHAR(50),
    NIV_URGENCE_DEFINITIF_TICKET VARCHAR(50),
    ETAT_TICKET VARCHAR(30) DEFAULT 'en_attente',
    HORODATAGE_CREATION_TICKET DATETIME CURRENT_DATE(),
    HORODATAGE_DEBUT_TRAITEMENT_TICKET DATETIME,
    HORODATAGE_RESOLUTION_TICKET DATETIME,
    HORODATAGE_DERNIERE_MODIF_TICKET DATETIME,
    FOREIGN KEY (ID_USER) REFERENCES Utilisateur (ID_USER),
    FOREIGN KEY (ID_TECHNICIEN) REFERENCES Utilisateur (ID_USER),
    FOREIGN KEY (ETAT_TICKET) REFERENCES EtatTicket (VALEUR_ETAT_TICKET)
);

-- Création de la table "Libelle"
CREATE TABLE Libelle (
    NOM_LIBELLE VARCHAR(50) PRIMARY KEY
);

-- Création de la table "RelationTicketsLibelles"
CREATE TABLE RelationTicketsLibelles (
    ID_TICKET INT,
    NOM_LIBELLE VARCHAR(50),
    PRIMARY KEY (ID_TICKET, NOM_LIBELLE),
    FOREIGN KEY (ID_TICKET) REFERENCES Ticket (ID_TICKET),
    FOREIGN KEY (NOM_LIBELLE) REFERENCES Libelle (NOM_LIBELLE)
);
