INSERT INTO Libelle VALUES("Matériel manquant");
INSERT INTO Libelle VALUES("Ordinateur HS");
INSERT INTO Libelle VALUES("Moniteur HS");
INSERT INTO Libelle VALUES("Clavier HS");
INSERT INTO Libelle VALUES("Souris HS");
INSERT INTO Libelle VALUES("Vidéoprojecteur HS");
INSERT INTO Libelle VALUES("Mot de passe Windows oublié");
INSERT INTO Libelle VALUES("Problème session Windows");
INSERT INTO Libelle VALUES("Problème connexion ethernet");
INSERT INTO Libelle VALUES("Session inexistante");
INSERT INTO Libelle VALUES("Piratage de ma session");
INSERT INTO Libelle VALUES("Virus sur ma session");
INSERT INTO Libelle VALUES("Mot de passe root Linux modifié");
INSERT INTO Libelle VALUES("Autre problème");
