-- LES VUES LIÉES AU TABLEAU DE BORD
CREATE OR REPLACE VIEW vue_tableau_bord AS
SELECT T.ID_TICKET, T.OBJET_TICKET, T.DESCRIPTION_TICKET, T.NIV_URGENCE_ESTIMER_TICKET, T.NIV_URGENCE_DEFINITIF_TICKET, T.ETAT_TICKET, T.HORODATAGE_CREATION_TICKET, T.HORODATAGE_DERNIERE_MODIF_TICKET,
       T.ID_TECHNICIEN, T.ID_USER as ID_CREA, CREA.PRENOM_USER as PRENOM_CREA, CREA.NOM_USER as NOM_CREA, TECH.PRENOM_USER as PRENOM_TECH, TECH.NOM_USER as NOM_TECH
FROM Ticket AS T
    JOIN Utilisateur AS CREA ON T.ID_USER = CREA.ID_USER
    LEFT OUTER JOIN vue_technicien AS TECH ON T.ID_TECHNICIEN = TECH.ID_USER
WHERE T.ETAT_TICKET = "Ouvert"
   OR T.ETAT_TICKET = "En cours de traitement"
   OR (T.ETAT_TICKET = "En attente" AND (T.ID_USER = substring_index(user(),'@',1) OR (SELECT role_user FROM vue_Utilisateur_client) = "role_admin_web"));

CREATE OR REPLACE VIEW vue_tdb_relation_ticket_libelle AS
SELECT RTL.ID_TICKET, RTL.NOM_LIBELLE
FROM RelationTicketsLibelles AS RTL
    JOIN vue_tableau_bord AS TDB ON RTL.ID_TICKET = TDB.ID_TICKET;



-- LES VUES LIÉES AUX MODIFICATIONS DES TICKETS

CREATE OR REPLACE VIEW vue_modif_creation_ticket_utilisateur AS
SELECT ID_TICKET,OBJET_TICKET, DESCRIPTION_TICKET, NIV_URGENCE_ESTIMER_TICKET, HORODATAGE_DERNIERE_MODIF_TICKET
FROM Ticket
WHERE ID_USER = SUBSTRING_INDEX(USER(), '@', 1)
AND ETAT_TICKET = 'En attente';

CREATE OR REPLACE VIEW vue_modif_ticket_adm_tech AS
SELECT ID_TICKET,OBJET_TICKET, DESCRIPTION_TICKET, ID_TECHNICIEN, ETAT_TICKET, NIV_URGENCE_DEFINITIF_TICKET, HORODATAGE_DERNIERE_MODIF_TICKET, HORODATAGE_RESOLUTION_TICKET
FROM Ticket
WHERE (ETAT_TICKET = "En cours de traitement" AND ID_TECHNICIEN = SUBSTRING_INDEX(USER(), '@', 1)) OR (ObtenirRoleUtilisateur() = ("role_admin_web" COLLATE utf8mb4_unicode_ci) AND (ETAT_TICKET != "Fermé"));

CREATE OR REPLACE VIEW vue_associe_ticket_tech AS
SELECT ID_TICKET, ID_TECHNICIEN, HORODATAGE_DEBUT_TRAITEMENT_TICKET
FROM Ticket
WHERE (ETAT_TICKET = "Ouvert");

CREATE OR REPLACE VIEW vue_modif_relation_ticket_libelle AS
SELECT RTL.ID_TICKET, RTL.NOM_LIBELLE
FROM RelationTicketsLibelles AS RTL
    JOIN vue_tableau_bord AS TDB ON RTL.ID_TICKET = TDB.ID_TICKET
WHERE ((SELECT role_user FROM vue_Utilisateur_client) != "role_utilisateur"
AND (SELECT role_user FROM vue_Utilisateur_client) != "role_admin_sys")
   OR TDB.ETAT_TICKET = "En attente";

CREATE OR REPLACE VIEW vue_historique AS
SELECT T.ID_TICKET, T.OBJET_TICKET, T.DESCRIPTION_TICKET, T.NIV_URGENCE_DEFINITIF_TICKET, T.ETAT_TICKET, T.HORODATAGE_CREATION_TICKET, T.HORODATAGE_DERNIERE_MODIF_TICKET, T.ID_TECHNICIEN, T.ID_USER, CREA.PRENOM_USER, CREA.NOM_USER, TECH.PRENOM_USER as PRENOM_TECH, TECH.NOM_USER as NOM_TECH
FROM Ticket AS T
    JOIN Utilisateur AS CREA ON T.ID_USER = CREA.ID_USER
    LEFT OUTER JOIN Utilisateur AS TECH ON T.ID_TECHNICIEN = TECH.ID_USER
WHERE T.ETAT_TICKET = "Fermé";


CREATE OR REPLACE VIEW vue_historique_relation_ticket_libelle AS
SELECT RTL.ID_TICKET, RTL.NOM_LIBELLE
FROM RelationTicketsLibelles AS RTL
    JOIN vue_historique AS H ON RTL.ID_TICKET = H.ID_TICKET;

CREATE OR REPLACE VIEW vue_technicien AS
SELECT ID_USER, PRENOM_USER, NOM_USER, EMAIL_USER
FROM DB_TIX.Utilisateur
JOIN mysql.user ON mysql.user.User = ID_USER
WHERE mysql.user.default_role = "role_technicien";
