GRANT SELECT(T.ID_TICKET, T.OBJET_TICKET, T.DESCRIPTION_TICKET, T.NIV_URGENCE_DEFINITIF_TICKET,
             T.ETAT_TICKET, T.HORODATAGE_CREATION_TICKET, T.HORODATAGE_DERNIERE_MODIF_TICKET, PRENOM_TECH, NOM_TECH)
ON vue_tableau_bord
TO 'role_utilisateur';

GRANT SELECT(T.ID_TICKET, T.OBJET_TICKET, T.DESCRIPTION_TICKET, T.NIV_URGENCE_DEFINITIF_TICKET,
             T.ETAT_TICKET, T.HORODATAGE_CREATION_TICKET, T.HORODATAGE_DERNIERE_MODIF_TICKET, PRENOM_TECH, NOM_TECH,
             ID_TECHNICIEN, ID_CREA, PRENOM_CREA, NOM_CREA)
ON vue_tableau_bord
TO 'role_technicien';

GRANT SELECT(T.ID_TICKET, T.OBJET_TICKET, T.DESCRIPTION_TICKET, T.NIV_URGENCE_DEFINITIF_TICKET,
             T.ETAT_TICKET, T.HORODATAGE_CREATION_TICKET, T.HORODATAGE_DERNIERE_MODIF_TICKET, PRENOM_TECH, NOM_TECH,
             ID_TECHNICIEN, ID_CREA, PRENOM_CREA, NOM_CREA)
ON vue_tableau_bord
TO 'role_admin_web';